class DB:
    def __init__(self, path, *args: list, **kwargs: dict) -> None: ...
    def _insert_statuses(self, *args: list, **kwargs: dict) -> None: ...
    def _create_tables(self, *args: list, **kwargs: dict) -> None: ...
    def _drop_tables(self, *args: list, **kwargs: dict) -> None: ...
    def execute(self, query: str, *args: list, **kwargs: dict) -> None: ...
    def close(self, *args: list, **kwargs: dict) -> None: ...
