from typing import Any

class IterClass:
    def __iter__(self, *args: list, **kwargs: dict) -> Any: ...
    def __next__(self, *args: list, **kwargs: dict) -> Any: ...
    def next(self, *args: list, **kwargs: dict) -> Any: ...
