# region import libraries
from .scheduler import Scheduler
from typing import Union

# endregion

class Router:
    def __init__(self, text: str, *args: list, **kwargs: dict) -> None: ...
    def __add__(self, instance: Scheduler, *args: list, **kwargs: dict) -> None: ...
    def __getitem__(
        self, value: Union[str, list], *args: list, **kwargs: dict
    ) -> Union[str, bool]: ...
    def _get_code(self, *args: list, **kwargs: dict) -> str: ...
    def _get_from(self, *args: list, **kwargs: dict) -> str: ...
    def _get_to(self, *args: list, **kwargs: dict) -> str: ...
    def __str__(self, *args: list, **kwargs: dict) -> str: ...
    def get_sql_values(self, *args: list, **kwargs: dict) -> list: ...
    @property
    def status(self, *args: list, **kwargs: dict) -> str: ...
