class Scheduler:
    def __init__(self, text: str, *args: list, **kwargs: dict) -> None: ...
    def _get_status(self, *args: list, **kwargs: dict) -> str: ...
    def _get_code(self, *args: list, **kwargs: dict) -> str: ...
    def __str__(self, *args: list, **kwargs: dict) -> str: ...
